workspaces:
  - name: Yuusoft
    projects:
      - name: Kanbatte
        url: https://kanbatte.yuusoft.com
  - name: RouteVN
    projects:
      - name: Route Graphics
        url: https://route-graphics.routevn.com
